### PR TITLE
(fix) lint & status: respect release filter

### LINKED ISSUE #1651: helm lint and list ignore enabled condition
`helmfile list` shows enabled while chart is disabled, same issue for `helm lint`, `helm lint` would try to lint releases with values for environments that is not enabled for.

```
helmfile version
helmfile version v0.137.0
```

```
helmfile -f helmfile.yaml -e staging list
NAME                        	NAMESPACE   	ENABLED	LABELS
kube-prometheus-stack       	xxxx  	true   	chart:kube-prometheus-stack
```

```
bases:
- ../envs/environments.yaml
releases:
- name: kube-prometheus-stack
  labels:
    chart: kube-prometheus-stack
  chart: ../charts/kube-prometheus-stack
  condition: prometheus.enabled
```
envs
```
prometheus:
  enabled: false
```

### PR DESCRIPTION
**Pull request by itscaro**
related to #1190 
fixes #1651 

@mumoshu I added some commits for styling / organisation, tell me if they should be dropped from this PR

### CODE REVIEW

**Comment by itscaro** [comment]
Hi @mumoshu, did you have time to have a look at this PR? Thank you for your time.

File: pkg/app/run.go [hunk 1]
```diff
@@ -245,7 +151,7 @@ func (run *Run) diff(triggerCleanupEvent bool, detailedExitCode bool, c DiffConf
 	for _, r := range changedReleases {
 		id := state.ReleaseToID(&r)
 
-		// If `helm-diff` detected changes but it is not being `helm delete`ed, we should run `helm upgrade`
+		// If `helm-diff` detected changes but it is not being `helm delete`ed, we should r `helm upgrade`
```
Comment (mumoshu) [inline pkg/app/run.go:154]:
```suggestion
		// If `helm-diff` detected changes but it is not being `helm delete`ed, we should run `helm upgrade`
```

Seems like an unnecessary change 👍

File: pkg/app/app.go [hunk 2]
```diff
@@ -1276,6 +1276,184 @@ Do you really want to delete?
...
+	}
+	if len(selectedReleases) == 0 {
+		return false, nil
+	}
+
+	// Do build deps and prepare only on selected releases so that we won't waste time
+	// on running various helm commands on unnecessary releases
+	st.Releases = selectedReleases
+
+	releasesToRender := map[string]state.ReleaseSpec{}
```
Comment (mumoshu) [inline pkg/app/app.go:1346]: This should have been `toLint` for consistency wit `func (a *App) test(r *Run, c TestConfigProvider) []error`. I appreciate it if you could fix this later 😃

File: pkg/app/app.go [hunk 3]
```diff
@@ -1475,6 +1653,31 @@ func (a *App) template(r *Run, c TemplateConfigProvider) (bool, []error) {
 	return true, errs
 }
 
+func (a *App) test(r *Run, c TestConfigProvider) []error {
```
Comment (mumoshu) [inline pkg/app/app.go:1656]: This could have better left not moved so that i was a bit easier for me to review 😉 (You didn't do anything except moving it to app.go so that it is located alphabetically next to `sync`, right?

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks a lot for your continuous support @itscaro!
